language: python
python:
  - "2.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "wget http://googleappengine.googlecode.com/files/google_appengine_1.7.0.zip"
  - "unzip google_appengine_1.7.0.zip"
# command to run tests
script: 
  - "APPENGINE_SDK=google_appengine python tests/runner.py tests"
