application: ismywebservicedown
version: 3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: .*
  script: main.py
  secure: optional

skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 (.*\.markdown)|
 (license\.txt)|
 (setup.py)
 )$